### ISSUE TITLE
Recording of the entire manual movement trajectory (including speed, pauses...)

### ISSUE THREAD

**Issue by KupchishinAB** [WinGs-Robotics/STR400-Studio#2]
As I see it, there is only motion recording by control points that I can set by hand.

But there is no obvious functionality where I can control the trajectory of the tool and the whole trajectory would be recorded.
Need a feature to record the entire trajectory and be able to replay it multiple times for actual using.

Also one universal robot obviously can have in memory many different trajectories for different jobs. It would be good to have a convenient interface for selecting the desired "GCode"/scrypt from the pre-recorded list ones, rather than selecting and pasting into a text field as now.

**Comment by ttopeor** [comment]
Hi KupchishinAB,

Thanks for your advice! We've developed an upgraded version of our software, WOS, which includes the features you suggested. Check out these videos to see it in action:

[Robotics and Tech Innovation](https://www.linkedin.com/posts/yuefeng001_robotics-techinnovation-raspberrypi-activity-7178519927115452416-FkdP?utm_source=share&utm_medium=member_desktop)
[Robot Teaching with WOS](https://www.linkedin.com/posts/yuefeng001_robotteaching-wos-str400-activity-7166593131491147776-NzEt?utm_source=share&utm_medium=member_desktop)

Interested in a web demo or beta testing? Contact us at [info@wingsrobotics.com](mailto:info@wingsrobotics.com). Let’s explore what's possible together.

**Comment by ttopeor** [comment]
Hi KupchishinAB,

Thanks for your advice! We've developed an upgraded version of our software, WOS, which includes the features you suggested. Check out these videos to see it in action:
[WOS Tech innovation](https://www.linkedin.com/posts/yuefeng001_robotics-techinnovation-raspberrypi-activity-7178519927115452416-FkdP?utm_source=share&utm_medium=member_desktop)
[WOS Realtime Teaching](https://www.linkedin.com/posts/yuefeng001_robotteaching-wos-str400-activity-7166593131491147776-NzEt?utm_source=share&utm_medium=member_desktop)

Interested in a web demo or beta testing? Contact us at [info@wingsrobotics.com](mailto:info@wingsrobotics.com). Let’s explore what's possible together.

> As I see it, there is only motion recording by control points that I can set by hand.
> 
> But there is no obvious functionality where I can control the trajectory of the tool and the whole trajectory would be recorded. Need a feature to record the entire trajectory and be able to replay it multiple times for actual using.
> 
> Also one universal robot obviously can have in memory many different trajectories for different jobs. It would be good to have a convenient interface for selecting the desired "GCode"/scrypt from the pre-recorded list ones, rather than selecting and pasting into a text field as now.
